name: 'medicare_cclf_connector'
version: '0.1.2'
config-version: 2

profile: illuminate_fabric_dev

vars:

  claims_enabled: true

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  medicare_cclf_connector:
     final:
       +materialized: table
     intermediate:
       +materialized: table
     staging:
       +materialized: view
  the_tuva_project:
    data_quality:
      +enabled: false       
